gui:
  branchColorPatterns:
    '^feature': green
    '^bugfix': yellow
    '^hotfix': red
  theme:
    selectedLineBgColor:
      - default
      - reverse
    selectedRangeBgColor:
      - default
      - reverse
