reporting: "off"
startuppopupversion: 1
gui:
  theme:
    lightTheme: false
    activeBorderColor:
      - cyan
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - default
      - reverse
    selectedRangeBgColor:
      - blue
keybinding:
  universal:
    filteringMenu: '<c-f>'
