# -- general settings
set -g mouse on
set -g mode-keys vi
set -g detach-on-destroy off
set -g allow-passthrough on
set -q -g status-utf8 on
setw -q -g utf8 on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 10000
set -ga update-environment '\
DISPLAY DBUS_SESSION_BUS_ADDRESS \
QT_IM_MODULE QT_QPA_PLATFORMTHEME \
SESSION_MANAGER \
XDG_CONFIG_HOME XDG_CACHE_HOME XDG_DATA_HOME\
XDG_MENU_PREFIX XDG_RUNTIME_DIR XDG_SESSION_CLASS \
XDG_SESSION_DESKTOP XDG_SESSION_TYPE XDG_CURRENT_DESKTOP \
XMODIFIERS \
FZF_DEFAULT_OPTS \
TMUX_THEME_COLOR \
TERM TERM_PROGRAM \
'

# -- plugin settings
set -g @dracula-military-time true
set -g @dracula-show-timezone false
set -g @dracula-tmux-ram-usage-label "󰘚 "
set -g @dracula-cpu-usage-label " "
set -g @dracula-ram-usage-label " "
set -g @dracula-plugins "tmux-ram-usage cpu-usage ram-usage time"
set -g @dracula-show-flags true
set -g @dracula-show-powerline true
set -g @dracula-transparent-powerline-bg true
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# -- resurrect settings
set -g @resurrect-save 'S'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '0'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @plugin 'dracula/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
# prefix + C-s to switch to use fzf to switch to a pane in any session
set -g @fzf_pane_switch_bind-key "C-s"
set -g @fzf_pane_switch_list-panes-format "window_index pane_title"
set -g @plugin 'kristijan/fzf-pane-switch.tmux'
# git clone https://github.com/tmux-plugins/tpm.git ~/.tmux/plugins/tpm
# prefix + I to install plugins and refresh tmux environment
# prefix + U to update plugins
# prefix + alt + u to remove/uninstall plugins not on the plugin list
run '~/.tmux/plugins/tpm/tpm'

# -- prefix
unbind C-b
set -g prefix 'C-s'

# -- kill server
bind Q kill-server

# -- reset keybindings to default
bind s choose-tree

# -- pane settings
set -g pane-border-status top
set -g pane-border-format " #{?window_zoomed_flag,⛶ ,}#T "
set-hook -g after-select-pane 'run-shell "tmux select-pane -T \"$(echo #{pane_current_path} | sed \"s|$HOME|~|\")\""'
set-hook -g after-split-window 'run-shell "tmux select-pane -T \"$(echo #{pane_current_path} | sed \"s|$HOME|~|\")\""'
set -g @accent_color "#bd93f9"
set -g @dim_color "#44475a"
set -g pane-active-border-style "fg=#{@accent_color}"
set -g pane-border-style "fg=#{@dim_color}"

# -- window management
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# -- swap window
bind -r < swap-window -t -1 \; select-window -t -1
bind -r > swap-window -t +1 \; select-window -t +1

# -- clear history
bind k send-keys -R \; clear-history
bind K send-keys -R \; clear-history \; send-keys C-l # send-keys "clear" Enter # messy

# -- copy mode
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-selection-no-clear
bind -T copy-mode-vi DoubleClick1Pane select-pane \; send-keys -X select-word \; send-keys -X copy-selection-no-clear
bind -T copy-mode-vi TripleClick1Pane select-pane \; send-keys -X select-line \; send-keys -X copy-selection-no-clear
